config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers
  
  resources :product, only: [:index, :show]
  resources :cart, only: [:index]
  resources :order
  
  post 'cart/item/:id(.:format)', :to => 'cart#add_item', :as => :cart_item
  delete 'cart/item/:id(.:format)', :to => 'cart#delete_item'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'product#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :cpf, presence: true
  validates :street, presence: true
  validates :number, presence: true
  validates :neighborhood, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :postalCode, presence: true
  
end

app/models/order.rb
class Order < ApplicationRecord
    after_save :update_inventory
    after_save :confirmation_email 
    after_save :inventory_email 
    after_save :cart_cleanup
    
    def update_inventory
        
    end
    
    def confirmation_email
        OrderMailer.confirmation_email(self).deliver_now
    end
    
    def inventory_email
        OrderMailer.inventory_email(self).deliver_now
    end 
    
    def cart_cleanup
        cart = Cart.find_by(customer_id: self.customer_id)
        cart.destroy!
    end
end

app/models/product.rb
class Product < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:firstName, :lastName, :username, :cpf, :street, :number, :complement, :neighborhood, :city, :state, :postalCode])
        devise_parameter_sanitizer.permit(:account_update, keys: [:firstName, :lastName, :username, :cpf, :street, :number, :complement, :neighborhood, :city, :state, :postalCode])

    end
    
    def after_sign_out_path_for(resource_or_scope)
      #did not find any other successful way to reset session
      session[:cart] = []
      root_path
    end
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    helper ApplicationHelper
    
    def index
        check
        @items = []
        session[:cart].each do |item|
            @items.push(get_item(item["id"]))    
        end
        @total = get_total
    end
    def get_item(id)
        @item = Product.find(id)
        return @item
    end 
    def check
        #had to hack devise on application controller, I had a conflit reading sessions after logout
        session[:cart] = [] unless session[:cart]
            
        if customer_signed_in?
            if Cart.exists?(customer_id: current_customer.id)
                @cart = Cart.find_by customer_id: current_customer.id
                session[:cart] = @cart.items
            end                
        end
    end
    def save
        totals = get_total
        if customer_signed_in? 
            if Cart.exists?(customer_id: current_customer.id)
                @cart = Cart.find_by customer_id: current_customer.id
                @cart.items = session[:cart]
                @cart.total = totals 
            else
                @cart = Cart.create(customer_id: current_customer.id, items: session[:cart], total: totals)
            end
            @cart.save
        end 
    end 
    
    def delete_item
        check
        product_id = params[:id]
        
        session[:cart].delete_if do |item| 
            true if item["id"] == product_id
        end 
        save
        redirect_to cart_index_path
    end
    
    def add_item
        check
        product_id = params[:id]
        price = params[:product_price]
        if !(find_item(product_id)) 
            item = {"id" => product_id, "price" => price, "qty" => "1"}
            session[:cart].push(item)
            save
        end 
        redirect_to cart_index_path
    end
    def get_total
        totals = 0.0
        session[:cart].each do |i|
            totals += i["price"].to_f
        end
        return totals
    end
    def find_item(product_id)
        finder = false
        return finder unless session[:cart]
        session[:cart].each do |i|
            finder = true if i["id"] == product_id
        end
        return finder
    end 
    
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController

end

app/controllers/order_controller.rb
class OrderController < ApplicationController
    helper ApplicationHelper
    
    before_action :require_login
    before_action :require_cart
    
    def index
        
    end
    
    def new
        @customer = Customer.find(current_customer.id)
        @items = get_cart
        @total = @cart.total
    end 
    
    def get_cart
        @cart = Cart.find_by customer_id: current_customer.id
        @items = []
        @cart.items.each do |item|
            item = get_item(item["id"])
            @items.push(item)
        end
        return @items
    end
    def get_item(id)
        @item = Product.find(id)
        return @item
    end 
        
    def show
         
    end
    
    def create
        #verificar se já existe um pedido.
        #unless Order.exists?(customer_id: current_customer.id)
            @cart = Cart.find_by customer_id: current_customer.id
            @items = get_cart
            @customer = Customer.find(current_customer.id)
            #salvar o pedido
            @order = Order.create(customer_id: current_customer.id, customer: @customer.to_json, items: @items.to_json, total_price: @cart.total)
            #destruir o carrinho no DB e zerar a sessão.
            session[:cart] = []
        #else
        #    redirect_to cart_index_path
        #end
    end
    def require_login
        unless customer_signed_in? 
            redirect_to new_customer_session_path
        end
    end
    
    def require_cart
        unless Cart.exists?(customer_id: current_customer.id)
            redirect_to new_customer_session_path
        end 
    end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  helper ApplicationHelper
  
  def index
    @products = Product.all
  end
  
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_currency(value)
        ActiveSupport::NumberHelper.number_to_currency(value, :unit => "R$", separator: ",")
    end
end

app/helpers/cart_helper.rb
module CartHelper
    def validate_items(items)
        
    end
    def validate_inventory(items)
        return true
    end
    
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/cart/index.html.slim
- unless @items.empty? 
    == form_for :order, :url => new_order_path(), method: "get" do
        div.row
            h1.col-12 Carrinho
            div.col-12
                | Produtos : #{@items.length}
            - @items.each do |item|
                div.col-12.col-lg-6.offset-lg-3
                    div.card.product-card.mb-3
                        div.row.no-gutters
                            div.col-4
                                ==image_tag "fallback_img.png", class: "cart-card-img"
                            div.col-8
                                div.card-body
                                    div.card-title = item.name
                                    div.card-subtitle.mb-2.text-muted = format_currency(item.price)
                                    div.card-text 
                                        | Quantidade: 1
                                    = link_to  cart_item_path(item.id), method: :delete do
                                        i.far.fa-trash-alt
                div.w-100
            div.col-12.col-lg-6.offset-lg-3
                span Total: 
                span == format_currency(@total)
            div.col-12.col-lg-6.offset-lg-3
                button#addToCart.btn.btn-primary.btn-block Finalizar Reserva    
            
- else
    p 
    | nenhum produto encontrado

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title Inventos
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

    == csrf_meta_tags
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    
    link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"

    == javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    

  body.d-flex.flex-column.h-100
    header.container-fluid
      nav.navbar.navbar-expand-md
        button.navbar-toggler type="button" data-toggle="collapse" data-target="#navLinks"
          i.fas.fa-bars
        = link_to  root_path, class: "navbar-brand abs"  do
          ==image_tag "Logo.png", class: "logo-img"
        
        div#navLinks.navbar-collapse.collapse
          ul.navbar-nav.ml-auto
            - unless customer_signed_in? 
              li.nav-item
                = link_to "Login", new_customer_session_path, class: "nav-link"
              li.nav-item
                = link_to "Cadastro", new_customer_registration_path, class: "nav-link"
            - else
              li.nav-item 
                = link_to "Minha Conta", edit_customer_registration_path, method: :get, class: "nav-link"
              li.nav-item 
                = link_to "Logout", destroy_customer_session_path, method: :delete, class: "nav-link"
        ul.navbar-nav
          li.nav-item
              = link_to cart_index_path do
                i.fas.fa-shopping-bag
            
    main.flex-shrink-0
      div.container
        == yield 

app/views/order/create.html.slim
div.row
    div.col-lg-6.offset-lg-3
        h1 Obrigado por comprar na Minion Store
        p Dentro de alguns momentos um e-mail confirmando a sua reserva vai chegar, confira todos os dados e aguarde o dia do lançamento dos minions! 
        p Então nossa equipe entrara em contato para confirmar seu metodo de pagamento e dados do envio.

app/views/order/new.html.slim
h1 Checkout

== form_for :order, :url => order_index_path() do |f| 
    div.row.checkout-cards
        div.col-lg-4
            div.card
                div.card-header Informações Pessoais
                div.card-body
                    p.card-text 
                        | Nome: #{@customer.firstName} #{@customer.lastName}

                    p.card-text
                        | CPF: #{@customer.cpf}
                        
        div.col-lg-4
            div.card 
                div.card-header Endereço
                div.card-body
                    p.card-text
                        | #{@customer.street}, #{@customer.number}
                        - unless @customer.complement.blank?
                            |, #{@customer.complement}
                        br
                        | #{@customer.neighborhood}
                        br
                        | #{@customer.city}, #{@customer.state}
                        br
                        | #{@customer.postalCode}
           
        div.col-lg-4.checkout-cart
            div.card
                div.card-header Carrinho
                div.card-body
                    - @items.each do |item|
                        div.card.mb-3.product-card
                            div.row.no-gutters
                                div.col-3
                                    ==image_tag "fallback_img.png", class: "cart-card-img"
                                div.col-9
                                    div.card-body
                                        h5.card-title = item.name
                                        p.card-text = format_currency(item.price)
                                        
                div.card-footer Total #{format_currency(@total)}
            button#addToCart.btn.btn-primary.btn-block type="submit" Finalizar Reserva
    
    
    

app/views/product/index.html.slim
div.jumbotron.jumbotron-fluid
    div.container
        h1.display-4 Os Minions estão chegando!
        p.lead a partir de 17/04 os minions vão chegar na nossa loja! 

h2 Reserve o seu Minion!

- unless @products.empty?
    div.row.product-list
      - @products.each do |product|
        div.col-md-3.col-6
            div.card.text-center
                = link_to product_path(product.id) do
                    ==image_tag "fallback_img.png", class: "card-img-top"
                div.card-body
                    = link_to product_path(product.id) do
                        div.card-title = product.name
                        div.card-text = format_currency(product.price)
- else
    p
     | No items found.  Please add some inventory.
       Thank you!
       

app/views/product/show.html.slim
div.product-detail
    == form_for :cart, :url => cart_item_path() do 
        = hidden_field_tag 'product_id', @product.id
        = hidden_field_tag 'product_qty', '1'
        = hidden_field_tag 'product_price', @product.price
        div.row
            div.col-lg-6.col-12
                ==image_tag "fallback_img.png", class: "product-detail-image"
            div.col-lg-6.col-12
                div.row
                    div.product-name.col-6.h1 == @product.name
                    div.product-price.text-muted.col-6.text-right.h1 == format_currency(@product.price)
                p
                    == @product.description
                   
                p 
                    button#addToCart.btn.btn-primary.btn-block type="submit" Reserve agora!